### ISSUE TITLE
Exception: Python version not supported: 3.8.2

### ISSUE THREAD

**Issue by M0dred** [Srinivas11789/PcapXray#55]
Python 3.8.2

sudo python3 Source/main.py 
Traceback (most recent call last):
  File "Source/main.py", line 12, in <module>
    from cefpython3 import cefpython as cef
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/cefpython3/__init__.py", line 64, in <module>
    raise Exception("Python version not supported: " + sys.version)
Exception: Python version not supported: 3.8.2 (v3.8.2:7b3ab5921f, Feb 24 2020, 17:52:18) 
[Clang 6.0 (clang-600.0.57)]

**Comment by xroax** [comment]
Im having the same issues, currently installing python2. I also get the an error when running the requirements.txt install

**Comment by Srinivas11789** [comment]
I think this depends on [fix here](https://github.com/cztomczak/cefpython/issues/546).
