### ISSUE TITLE
no visualization pf pcap file

### ISSUE THREAD

**Issue by AlphonesDamonlette** [Srinivas11789/PcapXray#59]
![Capture](https://user-images.githubusercontent.com/71391152/135706835-cc366dae-20b5-473f-81c7-5433013529ba.JPG)

**Comment by Srinivas11789** [comment]
Thanks for reaching out. Could you pls elaborate on the error in terminal logs/os details where you faced this? I just rechecked in ubuntu (fresh install) and works fine with py3.

* Verify if pcapxray has permissions for filesystem.

**Comment by AlphonesDamonlette** [comment]
TRACE:stem:Descriptors retrieved from http://45.66.33.45:80/tor/status-vote/current/consensus in 45.87s
Starting Graph Plotting
Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\graphviz\backend.py", line 170, in run
    proc = subprocess.Popen(cmd, startupinfo=get_startupinfo(), **kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Alphones R\PycharmProjects\PcapXray\Source/Module\plot_lan_network.py", line 57, in __init__
    self.draw_graph(option, to_ip, from_ip)
  File "C:\Users\Alphones R\PycharmProjects\PcapXray\Source/Module\plot_lan_network.py", line 599, in draw_graph
    f.render()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\graphviz\files.py", line 240, in render
    quiet=quiet)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\graphviz\backend.py", line 235, in render
    run(cmd, capture_output=True, cwd=cwd, check=True, quiet=quiet)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\graphviz\backend.py", line 173, in run
    raise ExecutableNotFound(cmd) from e
graphviz.backend.ExecutableNotFound: failed to execute 'dot', make sure the Graphviz executables are on your systems' PATH

Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "C:\Users\Alphones R\PycharmProjects\PcapXray\Source/Module\user_interface.py", line 333, in map_select
    self.generate_graph()
  File "C:\Users\Alphones R\PycharmProjects\PcapXray\Source/Module\user_interface.py", line 304, in generate_graph
    self.load_image()
  File "C:\Users\Alphones R\PycharmProjects\PcapXray\Source/Module\user_interface.py", line 319, in load_image
    self.img = ImageTk.PhotoImage(Image.open(self.image_file).resize(tuple(self.zoom),Image.ANTIALIAS))#.convert('RGB'))
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\PIL\Image.py", line 2968, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Alphones R\\PycharmProjects\\PcapXray\\Source/Module/Report\\test_All_All_All.png'

**Comment by AlphonesDamonlette** [comment]
and i am using visual studio code

**Comment by Srinivas11789** [comment]
Thanks for the context.
```
graphviz.backend.ExecutableNotFound: 
```
from 👆 I think you are missing the graphviz dependency.

Check [here](https://graphviz.org/download/) and [here](https://stackoverflow.com/questions/35064304/runtimeerror-make-sure-the-graphviz-executables-are-on-your-systems-path-aft)/[here](https://graphviz.org/doc/winbuild.html) to install in windows and add to system path. Worked fine with win10.
