### ISSUE TITLE
startup error

### ISSUE THREAD

**Issue by nmaphacker** [Srinivas11789/PcapXray#71]
Hello,
What is this error:

┌──(root㉿kali)-[~/PcapXray]
└─# python3 Source/main.py
Interactive graph in app wont work as python version/platform is not supported (will launch in default browser)
Traceback (most recent call last):
  File "/root/PcapXray/Source/main.py", line 52, in <module>
    main()
  File "/root/PcapXray/Source/main.py", line 41, in main
    base = Tk()
  File "/usr/lib/python3.10/tkinter/__init__.py", line 2299, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

**Comment by srixivas** [comment]
Hey @nmaphacker, looks like env specific, are you launching via SSH? Pls share about your env/setup. Thanks!
* similar `tkinter.TclError` discussion at [ref](https://github.com/scrtlabs/catalyst/issues/39)
